### ISSUE TITLE
无法编译/部署/生成

### ISSUE THREAD

**Issue by Lightczx** [xunkong/desktop#101]
### 问题描述

* MapTool 会阻止 选择正常的生成选项(Debug|x64,Debug|AnyCPU)
* c++ 项目会阻止主项目的生成，因为CsWinRT的xml文件无法正常读取
* 某些引用了c++项目的项目因此无法编译生成
* Readme 中描述的过程无法精确与实操匹配

### 复现步骤

```plain text
* 克隆项目
* 按Readme操作
```

### 备注

希望能尽快更新Readme的说明

**Comment by Scighost** [comment]
一直摸鱼一直爽
![91539617_p0](https://user-images.githubusercontent.com/61003590/167785505-923c6f44-19ec-4ecc-9c23-ca2e26dd520b.jpg)

**Comment by Scighost** [comment]
https://github.com/xunkong/desktop/dev

![2HQQMCD1WE DY8{NBW9}3IH](https://user-images.githubusercontent.com/61003590/182630346-23873349-bf0b-4781-95e3-f50598527c73.jpg)
