### ISSUE TITLE
即将砍掉的一些功能

### ISSUE THREAD

**Issue by Scighost** [xunkong/desktop#108]
为了提高性能，减少维护负担，将会逐步砍掉一些功能：

> 打勾的为已砍掉，剩下的保留

- [x] Microsoft App Center 用户统计 ~~（统计个毛线）~~
- [x] 寻空小地图（推荐使用[空荧酒馆](https://yuanshen.site/)）
- [x] 应用内背景图（性能消耗大户）
- [x] 工具箱页面（有用的功能将会移动到相应页面）
- [ ] 快速启动游戏（推荐使用[简单启动器](https://github.com/xunkong/SimpleLauncher)）
- [ ] 后台定时签到（启动应用时的签到仍会保留）
- [ ] 应用内通知
- [ ] 更新提醒

接下来将会简化数据库结构，不用担心丢失数据，然后准备上架微软商店。

> 欢迎在下方提出你的建议

**Comment by Samonyoge** [comment]
1、每日一图很喜欢，遇到好看的都存下来了，如果实在无法保存，可否麻烦告知是否有独立工具。
2、原来使用原神PLUS启动器，后面发现这里有相同的功能就把PLUS启动器删了，能只用一个挺方便的。

谢谢

**Comment by zangxycoding** [comment]
win10现版本的快速启动很好用啊  不想再另外下载新工具了

**Comment by Apocalypse233** [comment]
- 真的非常喜欢每日一图功能，每次打开看到好看的图片顺手存下来就感觉非常舒服
- 个人每天使用寻空的习惯大概是：打开寻空（mys签到）-存图片-打开mys每日素材小工具看一下今日素材-快速启动游戏-退出游戏、刷新一下旅行札记数据-退出寻空。启动器分离的话，我大概每天会将寻空和启动器都打开，是否考虑在启动器中加入一个类似“同时打开寻空”的功能，并在config.txt中控制呢
- 感谢您开发并持续维护这个小工具！

**Comment by HungryHighness** [comment]
每日一图才核心啊歪（

**Comment by zangxycoding** [comment]
每日一图可以做成相册那样的子页面  要用时再加载

**Comment by tuqige-dlk** [comment]
希望速速修复窗口不够大就不能看完整深渊挑战记录和角色信息的bug

**Comment by xiaoxiangtear** [comment]
每日一图千万别删啊，美图越多越好，这个功能最赞

**Comment by qakcn** [comment]
后台签到是否能够保留，或者做一个开关来设置是否开启？如果是因为要上微软商店的原因，那可否另外提供一个应用来提供此功能呢？
以上纯粹是我个人的愿望，作者可以完全不用理会。谢谢作者的付出，希望这个小工具越来越好。

**Comment by 1498551989** [comment]
赞同楼上所说的，我也希望能保留后台定时签到功能。
