### ISSUE TITLE
2022-07-05 晚间打开寻空闪退

### ISSUE THREAD

**Issue by Scighost** [xunkong/desktop#112]
这是我的锅，在修改每日一图的文件地址的时候弄错了格式，错误格式 `https:/file.xunkong.cc/...`，导致解析 uri 时出现异常，现已修复。
非常抱歉给您带来不好的体验。

**Comment by hhhqpalzm** [comment]
哦哦哦 没事 哈哈哈 遇到点bug正常 我还以为是我cookies过期导致的 自己捣鼓了一会 哈哈
感谢大大回复~~
