### ISSUE TITLE
没有下一步的按钮，卡在这了

### ISSUE THREAD

**Issue by anhcemi** [xunkong/desktop#113]
### 问题描述

如题

### 复现步骤

```plain text
打开寻空，下一步，到依赖组件那儿就过不去了（另外如果不是最大化的话，甚至在隐私和用户那一步就没有下一步的按钮了）
```

### 截图

![1](https://user-images.githubusercontent.com/61397871/178654379-3b8101f3-73b2-4833-a13b-820ee0f5fa9f.png)

### 系统版本

win10 20H2

### 寻空版本

最新

**Comment by Scighost** [comment]
窗口调大一点，按键被挡住了

**Comment by anhcemi** [comment]
> 窗口调大一点，按键被挡住了

已经最大化了呀。窗口调大可以解决隐私&用户数据那一页的问题，但是解决不了依赖组件那一页的

**Comment by Scighost** [comment]
那调整屏幕缩放到最小

**Comment by Scighost** [comment]
屏幕缩放和文字大小调到最小
设置 -> 系统 -> 屏幕
设置 -> 辅助功能 -> 文本大小

**Comment by anhcemi** [comment]
> 那调整屏幕缩放到最小

对哦，脑子抽了没想到

**Comment by anhcemi** [comment]
不过最好还是做一下适配吧，毕竟笔记本用户很多都是125%

**Comment by Scighost** [comment]
不同大小屏幕的布局问题是个坑，我也没办法考虑到所有情况，你遇到的问题会在下次更新时修复
