### ISSUE TITLE
1.0.0能不能添加之前0.2版的win10的实时便签磁贴，太需要了！

### ISSUE THREAD

**Issue by zeroabc** [xunkong/desktop#115]
### 你的建议

如题，这个才是最好用的功能！用的最多了

**Comment by Scighost** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/61003590/178673160-e83e6327-992f-45af-b2ce-fb62508a4319.png">

**Comment by zeroabc** [comment]
![image](https://user-images.githubusercontent.com/6105867/178674114-ad96bd95-884c-4d31-9f0e-747d2e3fdec6.png)
这是什么原因。新版本装完打开了，点击那个固定开始屏幕之后提示什么:7890积极拒绝。然后0.2旧版本刚刚卸载完了，重新打开1.0.0，再点那个固定开始屏幕就提示这个信息

**Comment by Scighost** [comment]
已修复
