### ISSUE TITLE
win10的实时便签磁贴能否点击刷新，而不是打开程序

### ISSUE THREAD

**Issue by zeroabc** [xunkong/desktop#117]
### 你的建议

如题，跟之前旧版一样。大佬更新的很快，抱拳了！

**Comment by Scighost** [comment]
投上您宝贵的一票 https://forms.office.com/r/JihvkXEBtf

**Comment by zeroabc** [comment]
> 

投了，必须刷新

**Comment by zeroabc** [comment]
> 投上您宝贵的一票 https://forms.office.com/r/JihvkXEBtf

其实关于这个投票，最最核心的问题是这个磁贴显示的信息不会自己刷新，那么用户点击刷新是一个解决办法。如果磁贴能自己定期刷新，也就不需要用户点击刷新的这个功能了
