### ISSUE TITLE
签到问题：「1不是布尔值」

### ISSUE THREAD

**Issue by hankzhangcn** [xunkong/desktop#122]
### 问题描述

无法签到。

### 复现步骤

```plain text
启动Xunkong
```

### 截图

[![j42u9O.png](https://s1.ax1x.com/2022/07/16/j42u9O.png)](https://imgtu.com/i/j42u9O)

### 系统版本

Windows 11 家庭中文版 21H2

### 寻空版本

1.0.1.0

**Comment by Scighost** [comment]
在设置页面重新开启签到
