### ISSUE TITLE
每次进入寻空都弹窗签到错误

### ISSUE THREAD

**Issue by readice** [xunkong/desktop#126]
### 问题描述

登录寻空之后弹窗签到错误，1.0.1更新说修复了这个错误但是我还是有这个问题

### 复现步骤

```plain text
启动寻空，弹窗  FormatException   签到   0 is not a valid value for Boolean.
```

### 截图

![LK@2C$7QU(N`RR1}%)4YW4U](https://user-images.githubusercontent.com/101871184/179436061-3bb34922-3c1d-4763-8f8c-626d734b0105.png)

### 系统版本

Windows 10 21H2

### 寻空版本

1.0.1

### 备注

请问是否是因为我已经在别处签到才会出现这个问题，那如果我不想要这个功能也不想被弹窗该如何解决（因为不是后台自动签需要开软件），今天看到已知问题里有写即使是关闭签到也会默认开启

**Comment by Scighost** [comment]
在设置页面重新开启签到

**Comment by readice** [comment]
> 在页面设置重新开启签到

确实有用，好迷
