### ISSUE TITLE
角色界面的交互功能建议

### ISSUE THREAD

**Issue by pbxs666** [xunkong/desktop#130]
### 你的建议

1.目前可以在横向角色栏上用鼠标滚轮滚动列表，但但有时候还是不习惯，建议增加鼠标拖动交互，就好比游戏里那样，按住拖动我感觉也比较符合习惯，当然滚轮滚动也可以，就是一般不这样操作。
![1](https://user-images.githubusercontent.com/47630168/179898194-a6eb9587-b00a-47e9-b23d-97e719e8be11.jpg)

2.点击左上角的展开按钮后可以展开列表，但关闭时还需要点击左上角的方形按钮，我建议增加点击旁边空白处就可以收起列表这一功能，也比较符合操作习惯。
![2](https://user-images.githubusercontent.com/47630168/179898384-8e380851-2d87-49fe-b855-c3da6356b897.jpg)
如图中所示，点击红色区域（即绿色网格之外的区域）收起列表。

最后非常感谢作者大大的刻晴牛杂店与寻空，今后也会持续关注与支持，谢谢啦！

**Comment by pbxs666** [comment]
另外，还有两个问题：
1.角色界面里旅行者没有天赋信息，是bug还是其他原因？
![3](https://user-images.githubusercontent.com/47630168/179899973-13f43b09-3d4a-4187-8e6a-558685b28d71.jpg)

2.埃洛伊的角色图背景色应该是红色的，这个应该是联动角色的原因，颜色不太一样。
![4](https://user-images.githubusercontent.com/47630168/179900078-900f0707-538a-4358-a04a-dbd84dde9716.jpg)
![5](https://user-images.githubusercontent.com/47630168/179900101-233e1ac9-a1d1-4531-81a3-4837c9dc14c9.jpg)

**Comment by Scighost** [comment]
感谢你的建议，下面我会对每条建议给出我的解释。

> 增加鼠标拖动操作

原神的操作逻辑很明显是以手机为基准设计的，桌面端的鼠标滚动操作几乎不能用，我们被迫习惯了鼠标拖动的操作。
但是寻空是一个桌面端的原生软件，一维列表的滚动操作很自然地应该使用鼠标滚轮，这是手机端和桌面端的操作逻辑的区别。
而在上下左右四个方向都需要移动的地方，我会选择使用点击拖动操作，比如图片预览和卡池历史表。
另外，顶栏的头像图标是需要能够点击的，增加拖动操作可能会造成误判。

> 侧栏展开时点击其他区域收起侧栏

你所指的其他区域并不是一个整体，而是很多个组件拼起来的部分，想要实现这个功能需要加入很多判断逻辑。
这个页面只是外观上和原神相似，但是操作逻辑没必要可以模仿。

> 荧妹妹的技能天赋

~~你想要的是风荧、岩荧还是雷荧~~
命座信息是米游社给的，技能天赋是我自己加的，旅行者的不同元素的技能都不同，就干脆不展示了。

> 埃洛伊的红色背景图

背景图根据角色星级自动选择，五星当然是黄色背景喽。 ~~特殊是不可能搞特殊的~~

**Comment by pbxs666** [comment]
OK，感谢大佬解答。
