### ISSUE TITLE
寻空无法安装

### ISSUE THREAD

**Issue by yibeiliang151** [xunkong/desktop#131]
### 问题描述

寻空无法安装

### 复现步骤

```plain text
按照https://xunkong.cc/help/desktop/ 的帮助文档，先安装了 WebView2 Runtime，尝试了很多次都无法完成安装，powershell 提示报错，不知道如何解决，尝试手动安装，证书添加成功后，还是无法安装。edge浏览器也已升级为Beta版本了。
```

### 截图

![bc](https://user-images.githubusercontent.com/107047034/180057095-87827e90-a6ad-4f4c-84ee-26974a4bf8b5.png)
![{4TY TUARR{JWYX`E N59EX](https://user-images.githubusercontent.com/107047034/180058957-1d4709e9-ba1b-44be-b69f-d84176687d19.png)

### 系统版本

windows 10 21H2 专业工作站版

### 寻空版本

1.0.2

**Comment by Scighost** [comment]
没装证书

**Comment by yibeiliang151** [comment]
> 



> 没装证书

装了证书还是弹出这个捏

**Comment by Scighost** [comment]
- 检查文件 `Xunkong.Desktop.Package_1.0.2.0_x64.msixbundle` 的 SHA256 是否为 `0C7FDD3338DF638662D082395E49F84FD0B5592331A7BE4859D6160921F21F83`
- 检查证书是否安装到 `本地计算机/受信任人`
