### ISSUE TITLE
网页无法添加NGA

### ISSUE THREAD

**Issue by 2497162852** [xunkong/desktop#135]
### 问题描述

1.0.2版寻空，网页小工具无法获取NGA标题图标，保存后显示加载网页小工具失败URI为空，且一直未响应

### 复现步骤

添加网页小工具
网址：https://bbs.nga.cn/thread.php?fid=793&ff=650
获取标题图标失败
手动添加后保存失败

### 截图

![CZH7 V7NNY1)9T R@ G_$P](https://user-images.githubusercontent.com/33111780/180447299-4be34734-249e-472a-9700-fad203d9b4cb.png)

![0(@)) 7C0OVMC14L5T6(JVC](https://user-images.githubusercontent.com/33111780/180447063-bc22fcde-21c4-4a81-956c-beef4e54002e.png)

### 系统版本

win10 20H2

### 寻空版本

1.0.2测载版

**Comment by Scighost** [comment]
NGA 的图标是这个 https://bbs.nga.cn/favicon.ico
