### ISSUE TITLE
「实时便笺磁贴」的投票结果 & 回复留言

### ISSUE THREAD

**Issue by Scighost** [xunkong/desktop#136]
## 投票结果

投票时间：2022-07-19 22:22:22 ~ 2022-07-22 23:59:59

| | 刷新磁贴 | 打开寻空 | 总计 |
| --- | --- | --- | --- |
| Windows 10 | 179 | 48 | 227 |
| Windows 11 | 93 | 63 | 156 |
| 总计 | 272 | 111 | 383 |

Windows 11 用户的投票不计入结果，有效票数 227 票，支持刷新磁贴的占比 78.8% 。
1.0.3 版本点击磁贴后将会刷新磁贴。

## 推荐

推荐一波**寻空小组件**，支持磁贴和 Xbox Game Bar（Win+G 打开的那个东西）

[点击下载](https://apps.microsoft.com/store/detail/%E5%AF%BB%E7%A9%BA%E5%B0%8F%E7%BB%84%E4%BB%B6/9PHN021FKW2T?hl=zh-cn&gl=CN)

## 回复留言

> 留言内容不多，就全部贴出来了

### 关于磁贴

> 便签可以自定义加一些其他的东西的监控，比如说计算周天几点合体力 周一几点才可以达到150 160体力之类的

不是有一个图标告诉你啥时候树脂满了吗

> 区分左右键 左键刷新磁贴  右键打开寻空
> 磁贴主界面为打开寻空，右键提供刷新功能
> 最好单独设置一个刷新键，然后点别的地方打开寻空
> 上面有个按钮刷新，点击其他地方是进入

磁贴不支持交互，也不支持自定义右键菜单。

> 添加实时便签操作指导把、

这有啥需要教的？

> 磁贴不能做成两个磁贴吗，一个是刷新的，一个是打开APP的，用哪个就应用哪个

你可以自己把烟绯头固定到开始菜单。

> 加个刷新磁贴并打开选项
> 加个开关
> 实在众口难调的话，要不要在设置里面让大家自己选？我是win10，可以把寻空的运行快捷方式贴在开始菜单，然后每次刷新要在寻空里面点好久

不想加。

> win11能做磁贴了吗？或者有没有可能做成能放进win11小组件窗口的真正意义上的“小组件”？
> win11的整个通知栏或桌面小插件？
> win11有解决方案吗？

微软还没有开放自定义小组件的功能。

> 如果他能自己刷新就好了
> 单独出个刷新按钮
> 如果和以前一样会自动刷新，那应该点击打开寻空

已经能自动刷新了。

> 可以做个大尺寸的吗，可以表现恢复进度条那种

我已经升级到 Windows 11，磁贴的外观不会再修改了。

### 关于签到

> 签到不要砍成打开签到啊啊啊啊，开机签到多好啊啊啊啊啊啊啊啊啊啊啊啊啊！！！！！！！！！！！！！

做不到，MSIX 框架没办法在一个确定的时间点运行后台任务。

> 希望能保留后台签到功能，或者另外推出一个小工具给有需要的人。
> 保留后台签到功能
> 自动签到太鸡肋，无法确保签到成功，建议改为手动签到并加到右键启动下面
> 大佬能不能保留后台签到啊？
> 可以加回后台自动查询每日签到功能吗，我现在保留旧版派蒙头的唯一原因就是有时候会忘记开新寻空签到，无论加不加只是个小建议，也谢谢大佬的辛勤付出!

1.0.2 版本已加入此功能。为了避免漏签，只能每两小时运行一次签到任务，并且只能保证任务间隔时间是两小时，而不是在整点运行。

### 其他

> 可以增加對國際服支持嗎~

我不玩国际服，所以除了祈愿记录外，其他和账号相关功能不支持国际服。

> 新版本，探索派遣的 时间提示显示不了

建议你单独提 issue

> 树脂或者其他计时类的项目到时间后自动向系统发送消息，就好比手游发送消息提示一般。在设置里可以自己决定该功能的开关。

不想加太多后台任务，你可以提个 issue，然后多拉几个人支持一下，说不准后续版本就加上了呢。

> 我觉得小程序可以再精简一些

哪有小程序？

> 在洞天宝钱满、质变仪可使用时在打开寻空后能够直接显示（弹窗，直接在主界面显示之类）

启动速度已经有点慢了，以后再考虑吧。

> 能否增加win11系统中从开始菜单快捷启动游戏的功能？

Windows 11 的开始菜单有两部分，**已固定**部分的图标右键菜单不会显示任何自定义内容，只有在**所有应用**的右键菜单中才能看到自定义内容。

> 真的挺好用一个功能 希望回归！

啥功能？

> 好耶

(❁´◡`❁)

**Comment by MeltryllisServant** [comment]
Win10 1.030 
点击磁贴似乎无法刷新，而且也不会打开寻空，新版本后点击磁贴功能好像没有任何反应
