### ISSUE TITLE
角色信息板块里每次点到雷电将军界面1-2秒后程序会卡住一会

### ISSUE THREAD

**Issue by pbxs666** [xunkong/desktop#138]
### 问题描述

如题，角色信息板块里每次点到雷电将军界面1-2秒后程序会卡住一会。其它角色没有这个问题。
我感觉可能跟雷神的天赋图标有关， 有一个无法烹饪的天赋，但是没有图标。
![微信截图_20220725122908](https://user-images.githubusercontent.com/47630168/180699130-175e9e14-4a6c-4579-b484-4227b637f1ff.png)

### 复现步骤

只要点击雷电将军这个角色，1-2秒后软件就卡住了，等一会就恢复正常。
点击其他角色的面板没有卡住，但再次点击雷神这个角色，程序又会卡住。

### 系统版本

Windows10 20H2

### 寻空版本

1.0.3.0 侧载版

### 备注

会不会跟雷神面板里缺失的天赋图标有关？

**Comment by Scighost** [comment]
无法复现你的问题

**Comment by pbxs666** [comment]
https://user-images.githubusercontent.com/47630168/180745132-a4421083-a12e-4b41-bf58-02a183e64e95.mp4

这是我这边的操作录屏

**Comment by pbxs666** [comment]
> 无法复现你的问题

作者大佬请看下上一楼，我发的视频，页面里上下滚动是为了直观展示是否卡主，其中两次点到雷神都卡住了。
下面我把任务管理器也录进去了，看看有无资源占用上的问题

**Comment by Scighost** [comment]
怎么会出现这种问题

![@J85($ TFXV{ZZ1`48A{`~L](https://user-images.githubusercontent.com/61003590/180759008-64f68489-d9d4-4b82-815a-8d03c081e405.jpg)

**Comment by Scighost** [comment]
我给这个天赋找了张图标，麻烦你再测试一下。

**Comment by pbxs666** [comment]
> 我给这个天赋找了张图标，麻烦你再测试一下。

已经OK了，不卡了。

果然我的直觉还是很准的嘛，就是图标问题，嘿嘿。
