### ISSUE TITLE
Arm64 支持

### ISSUE THREAD

**Issue by luojunyuan** [xunkong/desktop#139]
### 你的建议

win arm64系统上直接运行Release中的x64版本，出现一个黑色窗口随后就闪退了。

**Comment by Scighost** [comment]
已支持，但是不能保证能完美运行。

**Comment by luojunyuan** [comment]
成功运行！应用反应很快，非常好用便利。愿顺利上架microsoft store
![tempImage4yRTkQ](https://user-images.githubusercontent.com/28323948/181038467-cb225d27-86ba-4a7a-95a1-29dd2bcd70ab.gif)
