### ISSUE TITLE
你的标题

### ISSUE THREAD

**Issue by mma345** [xunkong/desktop#144]
### 问题描述

由于游戏内的抽卡记录只保留6个月，之前的记录没有办法通过json或excel导入，在1.0.0.0版本中没有抽卡记录通过json或excel导入的选项，尽快添加

### 复现步骤

抽卡记录右上角只有通过网站添加，没有办法通过本地json文件添加

### 截图

<img width="317" alt="image" src="https://user-images.githubusercontent.com/71984559/183038922-62d4bd30-ecd5-4c39-8f90-271860b92568.png">

并没有导入选项

### 寻空版本

1.0.0.0

### 备注

我认为这是一个很大的问题，因为这个本身看记录还是很好的，但是老记录没法添加很难受

**Comment by Scighost** [comment]
请先升级到1.0.3版本

**Comment by mma345** [comment]
已经更新到1.0.3版本，发现是不支持paimon.moe导出的excel数据是吗？这个网站算是比较大的国际上的统计网站，能添加对他导出的excel数据的支持会更好
