### ISSUE TITLE
网页小工具无法正常加载部分网页的部分功能

### ISSUE THREAD

**Issue by MaxwellYe0815** [xunkong/desktop#4]
[paimon.moe](https://paimon.moe/)无法加载Google drive API
![屏幕截图(2)](https://user-images.githubusercontent.com/64358442/155944375-c9391bae-17a2-4b3d-b932-d6b40b496163.png)

[anber project](https://ambr.top/chs)无法展开星期选项框
![屏幕截图(3)](https://user-images.githubusercontent.com/64358442/155944975-d63200d7-2a67-4c8e-9fe2-5daf6eaf30ae.png)

**Comment by Scighost** [comment]
派蒙无法加载 Google Drive 是因为我阻止了网页弹出窗口，在下个版本中会解决这个问题。
安柏无法展开下拉列表是 WinUI 的bug，微软已经修复，但不知道什么时候发布，暂时可以使用 `Alt+↓` 代替鼠标操作。
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1693

**Comment by Sakurakouji-Runa** [comment]
还有一个
[yuanshen.xin](https://yuanshen.xin/)无法输入密钥
![Snipaste_2022-03-23_11-45-52](https://user-images.githubusercontent.com/46081776/159620030-65c3ce3a-ce72-4938-bdde-386a53a664fd.png)

**Comment by Scighost** [comment]
问题已解决
