### ISSUE TITLE
【反馈】 更新0.1.3.0后，右键快速启动游戏按钮消失了

### ISSUE THREAD

**Issue by Sakurakouji-Runa** [xunkong/desktop#49]
寻空从0.1.2.0升级到0.1.3.0后，右键快速启动游戏按钮消失了。

更新：
![Snipaste_2022-04-17_20-48-32](https://user-images.githubusercontent.com/46081776/163714963-29fb1024-bbf2-4942-95e9-8a8d168830c1.png)

系统环境为（Beta渠道win11）：
版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎4/‎14
操作系统版本	22598.100
体验	Windows Feature Experience Pack 1000.22598.100.0

寻空版本号 0.1.7.1

最近重装了几次，问题依旧

**Comment by Sakurakouji-Runa** [comment]
应用内的“启动游戏”按钮能正常启动游戏
![Snipaste_2022-03-23_20-46-45](https://user-images.githubusercontent.com/46081776/159702645-b96fdaf8-23f2-4daf-8f5d-4ec5324f1699.png)

**Comment by Scighost** [comment]
0.1.4.0 版本解决这个问题了吗？

**Comment by Sakurakouji-Runa** [comment]
> 0.1.4.0 版本解决这个问题了吗？

没有
![Snipaste_2022-03-26_08-51-18](https://user-images.githubusercontent.com/46081776/160218063-a798088b-8240-4a23-a514-098c1dd57839.png)

**Comment by Scighost** [comment]
我没装win11，无法在本机上测试，你有两个方法：
- 重装寻空
- 自行编译调试

相关的代码在这里
https://github.com/Scighost/Xunkong/blob/d8bf9dc6eab2508a9bbdc02cb8073bcc007a25d1/src/Desktop/Desktop/App.xaml.cs#L229-L249

**Comment by ZoftTy** [comment]
Windows 11 专业版 22000.613 没有出现这个问题
操作系统版本 22000.613
Windows 功能体验包 1000.22000.613.0

**Comment by Lightczx** [comment]
@Scighost Windows 11 没有 JumpList，包括开始菜单，右键也无法呈现此类功能
只能去Windows反馈中心提建议了

**Comment by sunyink** [comment]
我的win10 2004这个功能也有问题，软件2.0正式版。通过“图标”、“任务栏”等地方→右键→“启动游戏”按钮or“预登陆账号”按钮，会提示“选择项目不可用，叫我删除这个快捷方式....”，然后通过软件内开启游戏可以正常进去。@Scighost

**Comment by Lightczx** [comment]
看了一下 win11 任务栏右键的jumplist还是有的 @Scighost

**Comment by sunyink** [comment]
> 看了一下 win11 任务栏右键的jumplist还是有的 @Scighost

嗯..？你可以从那里进入游戏吗，我这边虽然有按钮，但按了出错。

**Comment by Lightczx** [comment]
只有小地图，没有启动游戏

**Comment by sddiky** [comment]
我在一台早期就安装了寻空的电脑上一路升级上来到0.2.0.0，右键“启动游戏”菜单存在并正常工作。
今天在一台新电脑上安装，只要安装的版本高于0.1.1.0，右键启动游戏就会消失。即使是先安装0.1.1.0再安装新版升级，也会导致消失。不知道问题在哪里。

**Comment by Sakurakouji-Runa** [comment]
更新0.2.0.2后，右键快速启动又回来了

**Comment by Scighost** [comment]
> 更新0.2.0.2后，右键快速启动又回来了

终于修复成功了
