### ISSUE TITLE
原神3.7版本疑似丢失解锁帧率功能

### ISSUE THREAD

**Issue by xshaon** [xunkong/desktop#502]
### 问题描述

从今天更新完就发现没办法用高帧率了

### 复现步骤

就在你们软件的启动游戏启动，试了很多次了，也更新过原神本地文件

### 系统版本

Windows 11 22H2

### 寻空版本

1.3.8.0

### 日志

[log_20230524_190752.txt](https://github.com/xunkong/xunkong/files/11553916/log_20230524_190752.txt)
[log_20230523_122511.txt](https://github.com/xunkong/xunkong/files/11553920/log_20230523_122511.txt)

**Comment by Scighost** [comment]
请参考 #509 ，此 issue 将被关闭。
