### ISSUE TITLE
【反馈】 签到过程中出现错误

### ISSUE THREAD

**Issue by DavideSOGG** [xunkong/desktop#86]
完整的反馈信息可以帮你快速解决问题

### 问题描述

网络良好的状况下出现签到错误提示 尚未登录 无论自动还是手动签到。实际上签到成功（因为游戏中收到了邮件）

### 复现步骤

某一次登录cookies关闭再打开寻空就这样了，以后退出账号重新登录也会触发，原理不明。以前是签到成功的

### 预期行为

正常签到 签到成功提示

### 截图

![bandicam 2022-04-18 14-25-24-085](https://user-images.githubusercontent.com/28831997/163808898-8295c1e1-4f45-48c7-8937-9b833054b9f2.jpg)

### 系统及寻空版本

- 系统：Windows 10 专业工作站版 20H2 （19042.928）
- 寻空：0.1.7.1

### 日志

[log_20220418_140720.txt](https://github.com/Scighost/Xunkong/files/8505685/log_20220418_140720.txt)

**Comment by Scighost** [comment]
https://xunkong.cc/help/desktop/account

**Comment by DavideSOGG** [comment]
> https://xunkong.cc/help/desktop/accou

解决了，就是有点玄学。同样bbs的米游社个人中心，同样获取cookies为啥有时包含cookie token和account id 有时又没有呢。操作是完全一致的啊.....
