### ISSUE TITLE
【建议】 增加一个最小化到托盘的功能

### ISSUE THREAD

**Issue by DavideSOGG** [xunkong/desktop#88]
请开始你的表演，详细合理的建议才有可能“中标”

### 问题描述

什么地方让你觉得不好用-----没有不好用只是。。嗯。。。更好用

### 解决方案

增加一个最小化到托盘的功能

### 补充信息

好像不加也没什么影响，但加上就更完美了。

**Comment by Scighost** [comment]
你认为现在有哪个功能需要托盘和常驻后台呢？
