### ISSUE TITLE
【反馈】关闭小地图菜单后无法再次打开

### ISSUE THREAD

**Issue by klrito123** [xunkong/desktop#91]
### 问题描述

关闭小地图菜单后无法再次打开

### 复现步骤

```plain text
在小地图设置页面关闭小地图菜单后无法再次打开
```

### 截图

![image](https://user-images.githubusercontent.com/45893413/164126883-71fc62cb-2cb0-4afd-bbbd-dbca737622d8.png)

### 系统版本

win11 21H2

### 寻空版本

2.0.0

**Comment by Scighost** [comment]
快捷键 Alt+S 打开设置
